# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish release

on:
  # uncomment the following if you need to debug manual trigger
  # workflow_dispatch:
  release:
    types: [created]

jobs:
  # Build dev first
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci --force
      - name: Build for development
        run: npm run build --if-present
      - name: Run Test
        run: npm run test:unit

  # Build prod bundle and publish publicly
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci --force
      - name: Build for production
        run: npm run production --if-present
      - name: Run Test
        run: npm run test:unit
        env:
          # Set environment to production just in case
          NODE_ENV: production
      - name: The final publish step within dist folder
        working-directory: dist
        # This will publish the package and set access to public as if you had run npm access public after publishing.
        run: npm publish --access public
        env:
          # Get npm token from Github
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
